version: "3.3"

services:
  postgresql:
    container_name: postgresql-container
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: my_store
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin-container
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
