version: "3.3"

services:
  postgresql:
    container_name: postgresql-container
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: my_store
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
    volumes:
      - ./postgres_data/postgres:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin-container
    image: dpage/pgadmin4
    ports:
      - "9090:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root

  mysql:
    container_name: mysqldb-container
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: akanza
      MYSQL_PASSWORD: akanza
      MYSQL_DATABASE: my_store
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_PORT: "3306"
    ports:
      - 7800:3306
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin-container
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_USER: root
      PMA_PASSWORD: admin
      PMA_HOST: mysql
    ports:
      - 8080:80
